enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
arch = "arm64-v8a"
build-mode = "module"
included-patches = "'Anonymous story viewing' 'Hide explore feed' 'Hide navigation buttons' 'Hide suggested content' 'Open links externally' 'Disable story auto flipping'"
